name: 'Terraform GCP Infrastructure'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  basic_job:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout code
            uses: actions/checkout@v2
          
          - name: Echo a message
            run: echo "CI workflow triggered successfully!"
